{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "wakeplane",
  "resources": [
    "daemon-deployment.json",
    "daemon-service.json",
    "daemon-state-persistentvolumeclaim.json",
    "runner-deployment.json",
    "runner-service.json",
    "runner-state-persistentvolumeclaim.json",
    "wakeplane-namespace.json"
  ]
}
