{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../base",
    "storage-class.json"
  ],
  "patches": [
    {
      "target": {
        "kind": "PersistentVolumeClaim"
      },
      "patch": "- op: add\n  path: /spec/storageClassName\n  value: wakeplane-google-cloud"
    }
  ]
}
